### PR TITLE
GDAL 3.5.0

### PR DESCRIPTION
**Pull request by visr**
https://github.com/OSGeo/gdal/blob/v3.5.0/NEWS.md

### CODE REVIEW

**Comment by visr** [comment]
Fixed after rebuilding GDAL with a higher libcurl compat.

**Comment by visr** [comment]
From the release notes:

> Add read/write OGR Parquet (Apache Parquet) and 'Arrow' (Apache Arrow IPC File/Feather or stream) drivers. Only in CMake builds

I didn't switch the build over to CMakie yet, so they are not available. Also haven't checked what dependencies are needed for them to build.

**Comment by joa-quim** [comment]
I built GDAL with cmake a couple weeks ago and for geoparquet there is the extra dependency of the ``arrow`` lib (it's documented in GDAL) which looks like a complicated beast with many possible building options. I just used the basic ones and everything built, but did not do any further tests.

**Comment by evetion** [comment]
So the cmake build would also need to depend on something like https://github.com/JuliaPackaging/Yggdrasil/pull/918

**Pull request merged**
