### PR TITLE
Update generator scripts 2

### PR DESCRIPTION
**Pull request by melonedo**
This commit adds macros and makes it work on Windows.

### CODE REVIEW

**Comment by melonedo** [comment]
I generated in both linux and Windows, and I turns out `time_t` is different on the two platforms(`Clong` vs `Clonglong`).
Without more tests, I think the best choice might be using multi-platform configuration then.

cc @Gnimuc

**Comment by Gnimuc** [comment]
If `time_t` is the only one that is system-dependent, then using multi-platform is a bit overkill. I guess it's safe to define it as `const time_t = Int` in the prologue.jl.

**Comment by Gnimuc** [comment]
You could also take this as an example: https://github.com/maleadt/LLVM.jl/blob/master/res/missing_defs.jl

**Comment by melonedo** [comment]
Thanks! I will try it later.

**Comment by visr** [comment]
Thanks for this! I cherry picked both commits into #121. The `time_t` workaround is also used there.

**Pull request closed without merging**
