### PR TITLE
update README on using the utilities

### LINKED ISSUE #86: update README on using the utilities
This section should be updated now that since #82 we use Artifacts and no longer have a `deps.jl`:
https://github.com/JuliaGeo/GDAL.jl/tree/v1.1.4#using-the-gdal-and-ogr-utilities

edit: I removed the incorrect information for now, but it would be great to update it and put it back

### PR DESCRIPTION
**Pull request by visr**
Fixes #86

### CODE REVIEW

**Review by yeesian — APPROVED** [review]
Looks great!

**Comment by yeesian** [comment]
I think one of the examples you gave on Zulip was also super helpful for others:

```
GDAL.ogr2ogr_path() do ogr2ogr
    run(`$ogr2ogr -f "ESRI Shapefile" outputfile.dbf inputfile.csv`)
end
```

**Comment by visr** [comment]
Ah yes, thanks, I will add that example as well.

Do you think it would be useful to copy some of this documentation to https://yeesian.com/ArchGDAL.jl/dev/reference/#API-Utilities as well? Some of this is also available through libgdal, though sometimes these are just more convenient.

**Comment by yeesian** [comment]
> Do you think it would be useful to copy some of this documentation to https://yeesian.com/ArchGDAL.jl/dev/reference/#API-Utilities as well?

Yeah, I think so! I've been trying to think through end-to-end workflows more, and these are great

**Comment by yeesian** [comment]
> I've been trying to think through end-to-end workflows more, and these are great

In particular, in combination with https://github.com/yeesian/ArchGDAL.jl/issues/201 to set up wizards for introducing people to the different utilities.

**Pull request merged**
